name: GitHub Actions Tests
run-name: ${{ github.actor }} Is Testing Programs On GitHub Actions 🚀

on:
  pull_request:
    branches: ["Production"]
  push:
    branches: ["Production"]

jobs:
  Server-Program-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Actions Pipeline Triggered"
      - run: echo "🐧 Running On A Linux Server"

      - uses: actions/checkout@v4
      - name: Initialize Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          cd "${{ github.workspace }}/Scripts/"
          python -m pip install -r Requirements.txt
          python -m pip install setuptools

      - name: Test Server Application
        run: |
          cd "${{ github.workspace }}/Server/"
          python "Server Program.py"

      - name: Test Server Registrar
        run: |
          cd "${{ github.workspace }}/Server/"
          python "Register Server.py" "GitHub Actions Server" "3000"

      - name: Test Enterprise Server
        run: |
          cd "${{ github.workspace }}/Delta/Server/"
          python "Enterprise Server.py"

      - name: Print Test Result
        run: |
          echo "👨‍💻 Test Result : ${{ job.status }}"
  
  Test-Android-Application:
    needs: Server-Program-Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Actions Pipeline Triggered"
      - run: echo "🐧 Running On A Linux Server"

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Run Tests
        run: |
          cd "${{ github.workspace }}/Android/"
          chmod +x gradlew
          ./gradlew check
          
      - name: Print Test Result
        run: |
          echo "👨‍💻 Test Result : ${{ job.status }}"